{% set name = "Flask-SQLAlchemy" %}
{% set version = "2.5.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2bda44b43e7cacb15d4e05ff3cc1f8bc97936cc464623424102bfc2c35e95912

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python ==2.7 | >=3.5
    - pip
  run:
    - python ==2.7 | >=3.5
    - flask >=1.0.4
    - sqlalchemy >=1.2

test:
  imports:
    - flask_sqlalchemy

about:
  home: https://github.com/pallets/flask-sqlalchemy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Adds SQLAlchemy support to your Flask application
  dev_url: https://github.com/pallets/flask-sqlalchemy
  doc_url: https://flask-sqlalchemy.palletsprojects.com

extra:
  recipe-maintainers:
    - pmlandwehr
    - synapticarbors
