{% set name = "Flask-SQLAlchemy" %}
{% set version = "3.0.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2764335f3c9d7ebdc9ed6044afaf98aae9fa50d7a074cef55dde307ec95903ec

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - pip
    - pdm-pep517 >=1.0.0
  run:
    - python >=3.7
    - flask >=2.2
    - sqlalchemy >=1.4.18

test:
  imports:
    - flask_sqlalchemy
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/pallets/flask-sqlalchemy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Adds SQLAlchemy support to your Flask application
  dev_url: https://github.com/pallets/flask-sqlalchemy
  doc_url: https://flask-sqlalchemy.palletsprojects.com

extra:
  recipe-maintainers:
    - pmlandwehr
    - synapticarbors
